# Quiz 4

<font size='4'>

BIOS-584<br>
Nov 21, 2025

* Write down your name in a Markdown section.

Joseph Lee

In [2]:
import numpy as np
import pandas as pd
import os

## Preliminary

<font size='4'>
    
* There are six files stored under `Your own GitHub repository/data/Quiz4`.
* Import those six files using relevant functions in `Pandas`.

## Import Data

<font size='4'>

* Three lists named `study_id_ls`, `measure_date_ls`, and `duration_ls` have been initialized.
* Write a for loop to extract and append the values of `study_id`, `measure_date`, and `duration` to `study_id_ls`, `measure_date_ls`, and `duration_ls`, respectively.

In [4]:
study_id_ls = []
measure_date_ls = []
duration_ls = []

folder = "data/Quiz4"

file_names = ["data_1.txt", "data_2.txt", "data_3.txt", "data_4.txt", "data_5.txt", "data_6.txt"]

for file_name in file_names: 
    path = os.path.join(folder, file_name)
    temp_df = pd.read_csv(path)

    # extracts only the value from first row
    study_id_value = temp_df["study_id"][0]
    measure_date_value = temp_df["measure_date"][0]
    duration_value = temp_df["duration"][0]
    
    # adds the value to its specfic list
    study_id_ls.append(study_id_value)
    measure_date_ls.append(measure_date_value)
    duration_ls.append(duration_value)

#check
print(study_id_ls)
print(measure_date_ls)
print(duration_ls)

[np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1), np.int64(1)]
['2025-01-01', '2025-03-01', '2025-02-01', '2025-11-01', '2025-11-01', '2025-11-03']
[np.int64(100), np.int64(300), np.int64(200), np.int64(25), np.int64(20), np.int64(30)]

<font size='4'>

* Create a new Pandas Dataframe combining three lists and name it `input_df`.

In [14]:
input_df = pd.DataFrame({"study_id": study_id_ls, "measure_date": measure_date_ls, "duration": duration_ls})

input_df.shape

(6, 3)

<font size='4'>

* Show or print `input_df`

In [13]:
input_df

   study_id measure_date  duration
0         1   2025-01-01       100
1         1   2025-03-01       300
2         1   2025-02-01       200
3         1   2025-11-01        25
4         1   2025-11-01        20
5         1   2025-11-03        30

## Data Manipulation

<font size='4'>

* Reorder the dataframe by `measure_date` (earliest to latest) and then by `duration` (shortest to longest).

In [16]:
input_df = input_df.sort_values(by=["measure_date", "duration"], ascending=[True, True])

input_df

   study_id measure_date  duration
0         1   2025-01-01       100
2         1   2025-02-01       200
1         1   2025-03-01       300
4         1   2025-11-01        20
3         1   2025-11-01        25
5         1   2025-11-03        30

<font size='4'>

* Create a new column called `relative_time` by calculating the time difference in days between each of the measure date and the earliest one.

In [26]:
input_df["measure_date"] = pd.to_datetime(input_df["measure_date"]) #to convert to real actual dates

earliest_date = input_df["measure_date"].min() 
print(earliest_date) #should be 1/1/25

input_df["relative_time"] = (input_df["measure_date"] - earliest_date)
print(input_df["relative_time"])

0   2025-01-01
1   2025-02-01
2   2025-03-01
3   2025-11-01
4   2025-11-01
5   2025-11-03
Name: measure_date, dtype: datetime64[ns]
2025-01-01 00:00:00
0     0 days
1    31 days
2    59 days
3   304 days
4   304 days
5   306 days
Name: relative_time, dtype: timedelta64[ns]

<font size='4'>

* Reset the index column and remove the old index.

In [24]:
input_df = input_df.reset_index(drop=True)

## Final Data Visualization
<font size='4'>
    
* Display the final `input_df`.

In [25]:
input_df

   study_id measure_date  duration relative_time
0         1   2025-01-01       100        0 days
1         1   2025-02-01       200       31 days
2         1   2025-03-01       300       59 days
3         1   2025-11-01        20      304 days
4         1   2025-11-01        25      304 days
5         1   2025-11-03        30      306 days